version: 0.0
os: linux
files:
   - source: target/spring-boot-web-0.0.1-SNAPSHOT.jar
     destination: /home/ubuntu/deployjavaapp/
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 60
      runas: root

